spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/Firmy
    password: '12345'
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: create-drop

cors:
  allowUrl: "*"

jwt:
  secret: secret_code
  expirationTime: 30h

files-storage:
  path: 'AIProjekt/src/main/resources/files'

mail:
  admin: carclinic.superuser@gmail.com
  sender:
    password: jeaxxqzekdimquqx
    debug: false
    user: carclinic.superuser@gmail.com
    host: smtp.gmail.com
    port: 587
  add-appointment:
    subject: 'Dodano rezerwację usługi w serwisie CarClinic!'
    pathToMessage: '/content/mail/addAppointment_pl.html'
  cancel-appointment:
    subject: 'Zgłoszenie w CarClinic zostało anulowane!'
    pathToMessage: '/content/mail/cancelAppointment.html'

rest:
  connection:
    connectionRequestTimeout: 5s
    readTimeout: 10s