spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/Firmy
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: create-drop
cors:
  allowUrl: "*"
jwt:
  secret: secret_code
  expirationTime: 30h